services:
  postgres:
    image: postgres:16-alpine
    container_name: tetris
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tetrisuser
      POSTGRES_PASSWORD: tetrispassword
      POSTGRES_DB: tetrisdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tetris-network

volumes:
  postgres_data:

networks:
  tetris-network:
    driver: bridge
